repos:
-   repo: https://github.com/doublify/pre-commit-rust.git
    rev: v1.0
    hooks:
    -   id: fmt
    -   id: cargo-check
    -   id: clippy
        args: ["--", "-A", "clippy::redundant_field_names", "-D", "warnings"]
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.0.1
    hooks:
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: check-toml
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: ['--maxkb=1024']
    -   id: end-of-file-fixer
