[package]
name = "fuzz_elf_loader"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
td-loader = { path = "../../td-loader" }
afl = {version = "*", optional = true }

[features]
fuzz = ["afl"]