// Copyright (c) 2021 - 2024  Intel Corporation
//
// SPDX-License-Identifier: BSD-2-Clause-Patent

// Auto-generated by `td-layout-config`, do not edit manually.

/*
Memory Layout Example
Top of Low Memory: 0x80000000
+----------------------------------------+ <- 0x80000000
|               EVENT_LOG                |   (0x100000) 1 MB
+----------------------------------------+ <- 0x7FF00000
|           RELOCATED_MAILBOX            |   (0x2000) 8 kB
+----------------------------------------+ <- 0x7FEFE000
|           PAYLOAD_PAGE_TABLE           |   (0x20000) 128 kB
+----------------------------------------+ <- 0x7FEDE000
|                  ACPI                  |   (0x100000) 1 MB
+----------------------------------------+ <- 0x7FDDE000
|                  FREE                  |   (0x7D57D000) 1.96 GB
+----------------------------------------+ <- 0x2861000
|                PAYLOAD                 |   (0x2000000) 32 MB
+----------------------------------------+ <- 0x861000
|           PAYLOAD_PARAMETER            |   (0x1000) 4 kB
+----------------------------------------+ <- 0x860000
|        UNACCEPTED_MEMORY_BITMAP        |   (0x40000) 256 kB
+----------------------------------------+ <- 0x820000
|                 TD_HOB                 |   (0x20000) 128 kB
+----------------------------------------+ <- 0x800000
|               BOOTLOADER               |   (0x800000) 8 MB
+----------------------------------------+ <- 0x0
Total Usage: 0x2A83000 (42.51 MB)
*/

pub const TOTAL_USAGE: usize = 0x2A83000; // (42.51 MB)

// Runtime Layout Configuration
pub const BOOTLOADER_BASE: usize = 0x0;
pub const BOOTLOADER_SIZE: usize = 0x800000; // 8 MB
pub const TD_HOB_BASE: usize = 0x800000;
pub const TD_HOB_SIZE: usize = 0x20000; // 128 kB
pub const UNACCEPTED_MEMORY_BITMAP_BASE: usize = 0x820000;
pub const UNACCEPTED_MEMORY_BITMAP_SIZE: usize = 0x40000; // 256 kB
pub const PAYLOAD_PARAMETER_BASE: usize = 0x860000;
pub const PAYLOAD_PARAMETER_SIZE: usize = 0x1000; // 4 kB
pub const PAYLOAD_BASE: usize = 0x861000;
pub const PAYLOAD_SIZE: usize = 0x2000000; // 32 MB
pub const ACPI_SIZE: usize = 0x100000; // 1 MB
pub const PAYLOAD_PAGE_TABLE_SIZE: usize = 0x20000; // 128 kB
pub const RELOCATED_MAILBOX_SIZE: usize = 0x2000; // 8 kB
pub const EVENT_LOG_SIZE: usize = 0x100000; // 1 MB

pub const MEMORY_LAYOUT_CONFIG: &[(&str, usize, &str)] = &[
    // (name of memory region, region size, region type)
    ("Bootloader", 0x800000, "Memory"),
    ("TdHob", 0x20000, "Memory"),
    ("UnacceptedMemoryBitmap", 0x40000, "Memory"),
    ("PayloadParameter", 0x1000, "Memory"),
    ("Payload", 0x2000000, "Memory"),
    ("Acpi", 0x100000, "Acpi"),
    ("PayloadPageTable", 0x20000, "Reserved"),
    ("RelocatedMailbox", 0x2000, "Nvs"),
    ("EventLog", 0x100000, "Nvs"),
];
