[package]
name = "uefi-pi"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r-efi = "3.2.0"
r-uefi-pi =  { path = "../r-uefi-pi" }
scroll = { version = "0.10", default-features=false}
