[package]
name = "fake"
version = "0.1.0"
edition = "2018"
description = "A fake crate to pass github CI, will be removed later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
